namespace CustomData;

public enum ItemPlaceType
{
	IPT_Null,
	IPT_Bag,
	IPT_HotKeyBar,
	IPT_Equipment,
	IPT_ServantEqu,
	IPT_ServantInteraction,
	IPT_ServantInteraction2,
	IPT_ServantSkill,
	IPT_ConolyServantEquPersonel,
	IPT_ColonyServantInteractionPersonel,
	IPT_ColonyServantInteraction2Personel,
	IPT_ConolyServantSkillPersonel,
	IPT_ConolyServantEquTrain,
	IPT_ConolyServantInteractionTrain,
	IPT_ConolyServantSkillTrain,
	IPT_Hospital,
	IPT_Warehouse,
	IPT_Shop,
	IPT_ItemGet,
	IPT_HBStorage,
	IPT_HBEngineering,
	IPT_HBNPCEqu,
	IPT_HBNPCUse,
	IPT_HBNPCSkill,
	IPT_Repair,
	IPT_PublicInventory,
	IPT_CSStorage,
	IPT_ItemBox,
	IPT_DropItem,
	IPT_Rail,
	IPT_NPCStorage
}
