namespace AppearBlendShape;

public enum EMorphItem
{
	Min = 0,
	MinFace = 0,
	FaceWidth = 0,
	FaceThickness = 1,
	EyebrowLocation = 2,
	EyebrowDirection = 3,
	EyeDirection = 4,
	EyeSize = 5,
	NoseLocation = 6,
	NoseHeight = 7,
	NoseSize = 8,
	MouthLocation = 9,
	MouthSize = 10,
	MouthShape = 11,
	ChinWidth = 12,
	JawWidth = 13,
	MaxFace = 14,
	MinUpperbody = 14,
	Shoulder = 14,
	Breast = 15,
	UpperArm = 16,
	LowerArm = 17,
	Belly = 18,
	Waist = 19,
	TorsoUpperLeg = 20,
	MaxUpperbody = 21,
	MinLowerbody = 21,
	LegBelly = 21,
	LegWaist = 22,
	UpperLeg = 23,
	LowerLeg = 24,
	MaxLowerbody = 25,
	MinHand = 25,
	Hand = 25,
	MaxHand = 26,
	MinFoot = 26,
	Foot = 26,
	MaxFoot = 27,
	Max = 27
}
